# View definitions captured from GreyJones Project Template
# Last updated: 2026-03-27 13:06
# Do NOT edit this file manually - run Prepare-ViewDefinitions.ps1 instead
{
  "CommercialDocuments": {
    "GreyJones Documents": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": true,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Internal_x0020_Document_x0020_Number",
        "Revision",
        "Lifecycle_x0020_Status",
        "Title",
        "Document_x0020_Category1",
        "Field",
        "External_x0020_Document_x0020_Number",
        "Site",
        "Origin",
        "Project_x0020_Number",
        "Modified",
        "Created",
        "Editor"
      ]
    },
    "Internal Document Numbers": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" Ascending=\"FALSE\" /></OrderBy><Where><Neq><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" /><Value Type=\"Text\">NA</Value></Neq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Lifecycle_x0020_Status"
      ]
    }
  },
  "TransmittalsProject": {
    "Document Set Flat": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /></OrderBy><Where><Neq><FieldRef Name=\"ContentType\" /><Value Type=\"Computed\">Transmittal Document Set</Value></Neq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Editor"
      ]
    },
    "Transmitted Documents MetaData": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Format",
        "Number_x0020_of_x0020_Copies",
        "Size",
        "External_x0020_Document_x0020_Number",
        "Internal_x0020_Document_x0020_Number"
      ]
    },
    "Document Set": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": true,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "DocumentSetDescription",
        "Project_x0020_Phase",
        "Delivery_x0020_Method",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Send_x0020_Transmittal_x0020_Notification_x0020_to_x0020_Recipients"
      ]
    },
    "Transmitted Documents": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Editor"
      ]
    }
  },
  "ProjectDocuments": {
    "GreyJones Documents": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": true,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Internal_x0020_Document_x0020_Number",
        "Revision",
        "Lifecycle_x0020_Status",
        "Title",
        "Document_x0020_Category1",
        "Field",
        "External_x0020_Document_x0020_Number",
        "Site",
        "Origin",
        "Project_x0020_Number",
        "Modified",
        "Created",
        "Editor"
      ]
    },
    "Internal Document Numbers": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" Ascending=\"FALSE\" /></OrderBy><Where><Neq><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" /><Value Type=\"Text\">NA</Value></Neq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Lifecycle_x0020_Status"
      ]
    }
  },
  "SurveyData": {
    "GreyJones Images": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": true,
        "ViewQuery": "<OrderBy><FieldRef Name=\"ImageCreateDate\" Ascending=\"FALSE\" /><FieldRef Name=\"Area\" /></OrderBy><Where><Eq><FieldRef Name=\"ContentType\" /><Value Type=\"Computed\">GreyJones Image Content Type</Value></Eq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": true,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "ImageCreateDate",
        "Area",
        "Stage",
        "Site",
        "Project_x0020_Number",
        "Modified",
        "Editor"
      ]
    },
    "GreyJones Documents": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Internal_x0020_Document_x0020_Number",
        "Revision",
        "Lifecycle_x0020_Status",
        "Title",
        "Document_x0020_Category1",
        "Field",
        "External_x0020_Document_x0020_Number",
        "Site",
        "Origin",
        "Project_x0020_Number",
        "Modified",
        "Created",
        "Editor"
      ]
    },
    "Internal Document Numbers": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" Ascending=\"FALSE\" /></OrderBy><Where><Neq><FieldRef Name=\"Internal_x0020_Document_x0020_Number\" /><Value Type=\"Text\">NA</Value></Neq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Lifecycle_x0020_Status"
      ]
    }
  },
  "TransmittalsCommercial": {
    "Document Set Flat": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /></OrderBy><Where><Neq><FieldRef Name=\"ContentType\" /><Value Type=\"Computed\">Transmittal Document Set</Value></Neq></Where>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Editor"
      ]
    },
    "Transmitted Documents MetaData": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Format",
        "Number_x0020_of_x0020_Copies",
        "Size",
        "External_x0020_Document_x0020_Number",
        "Internal_x0020_Document_x0020_Number"
      ]
    },
    "Document Set": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": true,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "DocumentSetDescription",
        "Project_x0020_Phase",
        "Delivery_x0020_Method",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Send_x0020_Transmittal_x0020_Notification_x0020_to_x0020_Recipients"
      ]
    },
    "Transmitted Documents": {
      "Settings": {
        "Aggregations": "",
        "DefaultView": false,
        "ViewQuery": "<OrderBy><FieldRef Name=\"Transmittal_x0020_Number\" Ascending=\"FALSE\" /><FieldRef Name=\"Modified\" Ascending=\"FALSE\" /></OrderBy>",
        "Scope": 0,
        "RowLimit": 30,
        "ViewType": "HTML",
        "Paged": false,
        "JSLink": "clienttemplates.js",
        "Toolbar": ""
      },
      "Fields": [
        "DocIcon",
        "LinkFilename",
        "Title",
        "Internal_x0020_Document_x0020_Number",
        "External_x0020_Document_x0020_Number",
        "Field",
        "Site",
        "Document_x0020_Category1",
        "Revision",
        "Intent",
        "Required_x0020_Action",
        "Action_x0020_Status",
        "Origin",
        "Distributing_x0020_Party",
        "Receiving_x0020_Party",
        "Transmittal_x0020_Number",
        "Transmittal_x0020_Date_x0020_",
        "Contractual_x0020_Due_x0020_Date",
        "Lifecycle_x0020_Status",
        "Project_x0020_Number",
        "Editor"
      ]
    }
  }
}

