# Scripts/Prepare-ViewDefinitions.ps1
[CmdletBinding()]
param()

Write-Host "=== Preparing full view definitions from template sites ===" -ForegroundColor Cyan

# Load configs - same style as all your other scripts
$contentConfig = Import-PowerShellDataFile -Path "$PSScriptRoot\..\GreyJones.ProjectProvisioning\Config\ContentTypeMapping.psd1"
$appConfig = Import-PowerShellDataFile -Path "$PSScriptRoot\..\GreyJones.ProjectProvisioning\Config\AppConfig.psd1"

$cert = ConvertTo-SecureString -String $appConfig.CertificatePassword -AsPlainText -Force

# This will hold ALL view data (name + fields + settings)
$viewDefinitions = @{}

foreach ($channelKey in $contentConfig.ChannelConfigurations.Keys) {

    $chan = $contentConfig.ChannelConfigurations[$channelKey]

    if ($chan.ViewNames.Count -eq 0 -or -not $chan.SourceSiteForViews) {
        Write-Host "Skipping $channelKey (no views or no template source)" -ForegroundColor Gray
        continue
    }

    $templateUrl = $contentConfig.ChannelBaseUrl + $chan.SourceSiteForViews
    Write-Host "Connecting to template for $channelKey → $templateUrl" -ForegroundColor Yellow
    Write-Host "   Using document library: $($chan.LibraryName)" -ForegroundColor Yellow

    Connect-PnPOnline -Url $templateUrl `
        -ClientId $appConfig.ClientID `
        -Tenant $appConfig.Tenant `
        -CertificatePath $appConfig.CertificatePath `
        -CertificatePassword $cert `
        -ErrorAction Stop

    $channelViews = @{}   # Stores data for each view in this channel

    foreach ($viewName in $chan.ViewNames) {

        $templateView = Get-PnPView -List $chan.LibraryName `
            -Identity $viewName `
            -Includes "ViewQuery", "RowLimit", "Paged", "DefaultView", "Toolbar", "Scope", "Aggregations", "JSLink", "ViewType" `
            -ErrorAction SilentlyContinue

        if ($templateView) {
            $fields = $templateView.ViewFields | ForEach-Object { $_.ToString() }

            $settings = @{
                ViewQuery    = $templateView.ViewQuery
                RowLimit     = $templateView.RowLimit
                Paged        = $templateView.Paged
                DefaultView  = $templateView.DefaultView
                Toolbar      = $templateView.Toolbar
                Scope        = $templateView.Scope
                Aggregations = $templateView.Aggregations
                JSLink       = $templateView.JSLink
                ViewType     = $templateView.ViewType
            }

            $channelViews[$viewName] = @{
                Fields   = $fields
                Settings = $settings
            }

            Write-Host "  ✓ Captured view '$viewName' from library '$($chan.LibraryName)' - $($fields.Count) fields" -ForegroundColor Green
        }
        else {
            Write-Warning "View '$viewName' not found in library '$($chan.LibraryName)' on template $templateUrl"
        }
    }

    if ($channelViews.Count -gt 0) {
        $viewDefinitions[$channelKey] = $channelViews
    }

    Disconnect-PnPOnline
}

# ====================== SAVE TO CONFIG FILE (as clean JSON) ======================
$exportPath = "$PSScriptRoot\..\GreyJones.ProjectProvisioning\Config\ViewDefinitions.psd1"

# Save as JSON (simple and reliable)
$viewDefinitions | ConvertTo-Json -Depth 10 | Out-File -FilePath $exportPath -Encoding UTF8 -Force

# Add the helpful header comment
$header = @"
# View definitions captured from GreyJones Project Template
# Last updated: $(Get-Date -Format "yyyy-MM-dd HH:mm")
# Do NOT edit this file manually - run Prepare-ViewDefinitions.ps1 instead

"@
$header + (Get-Content $exportPath -Raw) | Set-Content $exportPath -Encoding UTF8 -Force

Write-Host "✅ Full view definitions saved to: $exportPath" -ForegroundColor Green
Write-Host "   (name + fields + settings captured from the correct document libraries)"